# Generated by Django 3.2.7 on 2022-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddHosteldetailosModel',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostelname', models.CharField(max_length=100)),
                ('hostelownername', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=100, null=True)),
                ('hostel_location', models.TextField(max_length=500)),
                ('hostel_description', models.TextField(max_length=500, null=True)),
                ('wifi', models.CharField(max_length=100)),
                ('water', models.CharField(max_length=100)),
                ('beds', models.CharField(max_length=100)),
                ('image1', models.ImageField(null=True, upload_to='images/')),
                ('image2', models.ImageField(null=True, upload_to='images/')),
                ('image3', models.ImageField(null=True, upload_to='images/')),
                ('image4', models.ImageField(null=True, upload_to='images/')),
                ('price', models.CharField(max_length=100)),
                ('rooms', models.CharField(max_length=100)),
                ('staff', models.CharField(max_length=100)),
                ('users', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'add_hostel_details',
            },
        ),
        migrations.CreateModel(
            name='HostelOwnerProfileModel',
            fields=[
                ('prof_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'hostel_owner_profile',
            },
        ),
        migrations.CreateModel(
            name='HostelOwnerRegisterModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Hostel_owner_details',
            },
        ),
    ]
