# Generated by Django 3.2.7 on 2022-07-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhosteldetailosmodel',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
